language: node_js
node_js: node
before_deploy:
- gem install mime-types -v 2.6.2
deploy:
  provider: heroku
  api_key:
    secure: PUHubUz5pr9Q0GQedtEvO0oGnCckEUOvmZ/pxlt4GKL6YIOCmEW/rZLHUrVwms0sBROAK5MVnBEQDU8OCawmk3o3dMLDMGXGhWbBz/gXUlx91yRsAWYoGIMeKnA1j8DHHeTDdQhfS26PbqYzDDmfsrBdGkRAb1YPddkzERjjyEmRVNd0pd3Zbyhmnia7FDWIOyTwezx5wzASh89cywp7n20E1is0amp4RPyzQQkQ17BZXKWabN4xQ4Ahqobq6ATd8vF7VG2dJMoSsMXMVDfET0qkGw809yGcEgHmkhNAjDAmzk3k4wq92YCjnyaYV4elgCCphAIBwlHUa3Rf+q4g3gAEfxxTM0ZsRcl5uZzL6ORu0iP8zs8O7zNwp2d4fT34wj9BTPWYvbaoCEOaztZ56vYUBptFey37PZ2QOGL+F2w3UeKkladKr582v/o3+1GtNqJREzAEsxgaXNAjYgMymwd/9fwNCcQKezE7b2GwCQd42u3nKH8MC7/uIpDUrTK96wUbVNJZTsF3nN+oSUKUwVwqru5TbUzuOwloiJyQ9/2qzBgM+p/QPUoMra4c4j23TMVQIS0dZ63ey15YYi+nc/hCwNdWXwHngAwA9YIrQJ/5kOYSDmfoqLkZbCNHOjz94A1Vp77sPKAOJEUwVuqBrKSeveHzhvwci3RP4+fQAoY=
  app: damp-peak-78290
  on:
    repo: d-hongbro/node-shopping-list-integration-tests