language: node_js
node_js: node
before_deploy:
- gem install mime-types -v 2.6.2
deploy:
  provider: heroku
  api_key:
    secure: SxRbyM6ll36rPNzAGsHVcGCJF3dNoivrN1rUOdOHYmy1PoDNLoR5jAQFP7sJh3uLnNMq41bkwLq6hw2fzGyMAHmqjXtdDOPwUj1DWU6Dq0aAtJ2cEZcNJiuPHKBZTqillZCCrpPighXjUNJId6VkhlI8B7Kmlv8tnuoM40KzZTALVPHBlmUuQ9lph+PJKJ1IZS7ma9dl9fBnPKf0Ex5egyqOx9dQ3jxCbxgwWz/Bhqm9erLONHaoqac34RRbZiKjxvCUeqjp4tASwSSg4xrtpsyOZXYlpkMkSw6Yz7CSmJ9i2vB0qfnGNfGA5K78AzPd3lkKnQJ1oi2OEhpbFWY/PrmhwJIrcMOXdCuZWd9Bbb6otRwOGIULirWkTWXI8PY53GqTCWJdo7+YiDFYuV2JCkSWT1WlkewbMJFoDrx7SKtK1UivKHv5nNGVYLR4lA7DOYQxOZNqpdlNNis2NRmjEdXNSLRwz9fVi33HqdFD0eloILFAZon2TksQLqxPSILBF27g7Pe/AZFfDumENMULYTN3nZKZWncrxIBNMademDp5wPfj3NW2bQDomjW4ddAk4JqjvD0EJg+EuR1dQTZ40qoPgXpThcHql0ZnROzf0xsI22Rm3pEYng+0eBv5TcQPooMnQrFi2qRc3oOcxqZ8wliBlLQHCaymvUhQV6oGlCI=
  app: https://damp-peak-78290.herokuapp.com/
  on:
    repo: d-hongbro/node-shopping-list-integration-tests
