language: node_js
node_js: node
before_deploy:
- gem install mime-types -v 2.6.2
deploy:
  provider: heroku
  api_key:
    secure: HtwjkH0v7aDdEFXlmL+iXpKnJMLc3McqwU5MTyXVygYwgj1infMch7mJ3Oyvv+fuALJ2MHcs5ST0em1/2woPxk4yZBI89vvWD7sdoVJbC/y+aA3T3eOO5p4j8RjpmNlEkCVvgIi795gxMdVAXPEmFg2QTzNwhuBNtZhVGyca6eXFY3q+s/gePecL4wcLfLTPwEl6gcrmPO/E+dEG42Zjt6Masswz+jYLquQfwAID3yq/6qKntDlKc41Cu07+i7lKXUUVfGYH3zI+FlVbrPGEzGGvxxjwkOcC6Px2ltUeJ3vre/Spf5a5dn2+PYo8s1t831+wvJ2XpoK4JjL7OnyLbV/rvHuj2ZsfV3Ilq6iHOmahtQOnMalx72635RoM8y/s0wLEbIDy86D/u80M5youkPnnM7upCka0ZLk890HHZshTfFA6EfB/2lcgu+t9iwDq6SMeYDkmczfGysUgDt5I0PPedtGfXr0/b1xTLuZdwe8ZPhW4wBXegY6I/sgSeYk8h/S8cKYzg+I85lG/69Oqiz/qhL9DeNW4P7sh9iWc1m03T6dMSa3yvmXGz0nLwCr7pCuWLIuF1EK/kJlPu+sV/1e4GZtYmQvWLMwhpczcpYt9qyAbs2flztHzR7sUfy/hMCaxr8WGKTmPS1w5p57vmwq1FY4tNCWkr+gphZ7uMSU=
  app: node-shopping-list-integration-tests
  on:
    repo: d-hongbro/node-shopping-list-integration-tests
